### ISSUE TITLE
Date format Problem in Soap-Client , automatic Z added in Date Formate

### ISSUE THREAD

**Issue by hrushikesh-udchalo** [loopbackio/strong-soap#354] opened 2022-01-28 05:12 UTC
what i have send 
`
const request = {
...,
TravelDate: new Date('2022-02-08'),
...
}
`
last request xml= >
`<TravelDate>2022-02-08Z</TravelDate>`

**Comment by achrinza** [comment] 2022-01-28 10:52
I have re-opened https://github.com/loopbackio/strong-soap/issues/289 and will continue tracking the issue there.

**Comment by achrinza** [comment] 2022-01-28 10:52
Duplicate of #289

**Closed by achrinza** 2022-01-28 10:52 UTC
